name       : mutagen
version    : 1.46.0
release    : 15
source     :
    - https://github.com/quodlibet/mutagen/archive/refs/tags/release-1.46.0.tar.gz : 734455642e734983353a85ec6e00c809564c63e53ec10cffc1152d51dd576b5e
homepage   : https://github.com/quodlibet/mutagen
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python module for handling audio metadata
description: |
    Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC, MP4, Monkey's Audio, MP3, Musepack, Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files.
builddeps  :
    - python-hypothesis
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
