name       : mutagen
version    : 1.29
release    : 3
source     :
    - https://pypi.python.org/packages/source/m/mutagen/mutagen-1.29.tar.gz : dbad61c8db882f849f25183448f21e440f5eceaf614dd8c2c5ae9392f33f599f
license    : GPL-2.0
summary    : Python Mutagen
description: |
    Python Mutagen
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
