name       : mutagen
version    : 1.41.0
release    : 9
source     :
    - https://github.com/quodlibet/mutagen/releases/download/release-1.41.0/mutagen-1.41.0.tar.gz : dab6038c7f0e17c1b67fb8f56303e8be21e73ac47760f1a8e716856f1bdf5057
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python 2/3 module for handling audio metadata
description: |
    Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC, MP4, Monkey's Audio, MP3, Musepack,
    Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files.
builddeps  :
    - pycodestyle
    - pyflakes
    - python-hypothesis
    - python-pytest
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        py.test3
    popd
