name       : mutagen
version    : '1.37'
release    : 5
source     :
    - https://github.com/quodlibet/mutagen/archive/release-1.37.tar.gz : 693a2d619df4b422a8571d4917a9f3e3eaabea98be8fb6d75dec758707b2e79e
license    : GPL-2.0
component  : programming.python
summary    : Python 2/3 module for handling audio metadata
description: |
    Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC, MP4, Monkey's Audio, MP3, Musepack,
    Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
