name       : mutagen
version    : '1.36'
release    : 4
source     :
    - https://github.com/quodlibet/mutagen/archive/release-1.36.tar.gz : af2674e6bee30a544c487f2a61da27b1d6e8eab455fa21e21fbda7429c754eb2
license    : GPL-2.0
component  : programming.python
summary    : Python 2/3 module for handling audio metadata
description: |
    Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC, MP4, Monkey's Audio, MP3, Musepack,
    Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
