name       : mutagen
version    : 1.43.1
release    : 12
source     :
    - https://github.com/quodlibet/mutagen/releases/download/release-1.43.1/mutagen-1.43.1.tar.gz : d873baeb7815311d3420aab0a1d83f050f628228cbc2d6045a14a16460411bc9
homepage   : https://github.com/quodlibet/mutagen
license    : GPL-2.0-or-later
component  : programming.python
summary    : Python 2/3 module for handling audio metadata
description: |
    Mutagen is a Python module to handle audio metadata. It supports ASF, FLAC, MP4, Monkey's Audio, MP3, Musepack, Ogg Opus, Ogg FLAC, Ogg Speex, Ogg Theora, Ogg Vorbis, True Audio, WavPack, OptimFROG, and AIFF audio files.
builddeps  :
    - pycodestyle
    - pyflakes
    - python-hypothesis
    - python-pytest
    - python-setuptools
setup      : |
    rm tests/quality/test_pep8.py
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
       py.test
    popd

    pushd $PKG_BUILD_DIR/py3build
        py.test3
    popd
